## Language model

model:
  model_name: "transformers/Qwen/Qwen2-0.5B"
  model_revision: "main"
  model_dtype: "torch.bfloat16"

evaluator:
  evaluator_name: "mock_lm_eval_with_ppl"
  evaluator_metrics:
     - "ppl"
     - "arc_challenge"
  evaluator_seed: 271828

pareto_optimization:
  optimizer_seed: 173205
  pop_size: 2000
  n_gen: 50

sampler:
  algorithm: "random"
  quality_evaluator_metric: "arc_challenge"
  cost_metric: "parameters"
  random_bp_config_rng_seed: 314159
  max_num_changes_factor: 0.5
  num_ranked_candidates: 1000
  max_random_config_trials: 20

  n_val_rand: 128

  trn_schedule:
    - n_trn_onel: -1
      n_trn_rand: 128
      n_trn_actl: 0
      n_trn_parf: 0

    - n_trn_onel: 0
      n_trn_rand: 32
      n_trn_actl: 0
      n_trn_parf: 0
